apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  name: ecr-cred-helper-cronjob-rust
  namespace: utils
spec:
  suspend: false
  schedule: "0 */8 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          containers:
            - name: ecr-cred-helper
              image: bloveless/ecr-credential-helper:0.6.0-alpha.6
              imagePullPolicy: IfNotPresent
              env:
                - name: AWS_ACCOUNT_ID
                  value: "391324319136"
                - name: AWS_DEFAULT_REGION
                  value: us-west-2
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-access-keys-secret
                      key: secretAccessKey
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-access-keys-secret
                      key: accessKeyId
                - name: EMAIL
                  value: brennon.loveless@gmail.com 
                - name: NAMESPACES
                  value: "javascript30,fritzandandre,snippetbox,mockrift-com"
